# Generated by Django 4.0.3 on 2022-03-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='youtube_link',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
