# Generated by Django 4.0.3 on 2022-03-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_aula_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='youtube_link',
            field=models.CharField(max_length=50),
        ),
    ]
